CREATE TABLE refresh_tokens(
	id SERIAL PRIMARY KEY
	, user_id INT REFERENCES users(id)
	, token TEXT NOT NULL UNIQUE
	, expired_at TIMESTAMPTZ NOT NULL
	, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);